import BitwardenKit
import Foundation
import Testing

/// Tests for `SDKVersionInfo`.
struct SDKVersionInfoTests {
    /// `version` is not "Unknown" since the build script should have generated it.
    @Test
    func versionIsNotUnknown() {
        #expect(
            SDKVersionInfo.version != "Unknown",
            "SDK version should be generated by build script, not 'Unknown'",
        )
    }

    /// `version` is not empty.
    @Test
    func versionIsNotEmpty() {
        #expect(!SDKVersionInfo.version.isEmpty)
    }

    /// `version` matches the expected semantic version format from project-common.yml.
    /// Supports upstream build identifiers and the public fork's alias prerelease identifiers.
    /// Example: "2.0.0-3659-948b207"
    @Test
    func versionMatchesSemanticVersionFormat() {
        let version = SDKVersionInfo.version

        // Accept the two SDK version schemes we publish, retaining a required prerelease identity.
        let pattern = #"^\d+\.\d+\.\d+-(?:\d+-[a-f0-9]+|alias-provider-neutral\.\d+)$"#

        let regex = try? NSRegularExpression(pattern: pattern, options: [])
        let range = NSRange(version.startIndex..., in: version)
        let matches = regex?.firstMatch(in: version, options: [], range: range)

        #expect(
            matches != nil,
            "SDK version '\(version)' should identify an upstream build or public-fork alias prerelease",
        )
    }
}
