import BitwardenSdk
import Foundation
import XCTest

@testable import BitwardenShared

final class ForwardedEmailAliasGeneratorTests: BitwardenTestCase {
    override func tearDown() {
        AliasTestURLProtocol.handler = nil
        super.tearDown()
    }

    private func makeGenerator() -> ForwardedEmailAliasGenerator {
        let configuration = URLSessionConfiguration.ephemeral
        configuration.protocolClasses = [AliasTestURLProtocol.self]
        return ForwardedEmailAliasGenerator(session: URLSession(configuration: configuration))
    }

    /// Addy.io retains its nested acknowledgement and authenticated self-hosted request contract.
    func test_generateAddyIo_preservesProviderContract() async throws {
        let provider = AliasProviderTestState()
        AliasTestURLProtocol.handler = { request in
            provider.record(request)
            XCTAssertEqual(request.url?.absoluteString, "https://addy.example/api/v1/aliases")
            XCTAssertEqual(request.httpMethod, "POST")
            XCTAssertEqual(request.value(forHTTPHeaderField: "Authorization"), "Bearer provider-token")
            XCTAssertEqual(request.value(forHTTPHeaderField: "X-Requested-With"), "XMLHttpRequest")
            let body = try AliasTestURLProtocol.jsonBody(request)
            XCTAssertEqual(body["domain"] as? String, "example.com")
            XCTAssertEqual(body["description"] as? String, "Website: shop.example. Generated by Bitwarden.")
            return .json(["data": ["email": "Alias@Example.com"]])
        }

        let address = try await makeGenerator().generate(
            service: .addyIo(apiToken: "provider-token", domain: "EXAMPLE.com", baseUrl: "https://addy.example/"),
            website: "shop.example",
        )

        XCTAssertEqual(address, "alias@example.com")
        XCTAssertEqual(provider.recordedRequests().count, 1)
    }

    /// Firefox uses token authentication and returns a full address rather than a local part.
    func test_generateFirefox_preservesProviderContract() async throws {
        AliasTestURLProtocol.handler = { request in
            XCTAssertEqual(request.url?.absoluteString, "https://relay.firefox.com/api/v1/relayaddresses/")
            XCTAssertEqual(request.httpMethod, "POST")
            XCTAssertEqual(request.value(forHTTPHeaderField: "Authorization"), "Token provider-token")
            let body = try AliasTestURLProtocol.jsonBody(request)
            XCTAssertEqual(body["enabled"] as? Bool, true)
            XCTAssertEqual(body["generated_for"] as? String, "shop.example")
            return .json(["full_address": "Alias@Example.com"])
        }

        let address = try await makeGenerator().generate(
            service: .firefox(apiToken: "provider-token"), website: "shop.example",
        )

        XCTAssertEqual(address, "alias@example.com")
    }

    /// Forward Email preserves Basic authentication and domain/path response composition.
    func test_generateForwardEmail_preservesProviderContract() async throws {
        AliasTestURLProtocol.handler = { request in
            XCTAssertEqual(request.url?.absoluteString, "https://api.forwardemail.net/v1/domains/example.com/aliases")
            XCTAssertEqual(request.httpMethod, "POST")
            XCTAssertEqual(request.value(forHTTPHeaderField: "Authorization"), "Basic cHJvdmlkZXItdG9rZW46")
            XCTAssertEqual(try AliasTestURLProtocol.jsonBody(request)["labels"] as? String, "shop.example")
            return .json(["name": "Alias", "domain": ["name": "example.com"]])
        }

        let address = try await makeGenerator().generate(
            service: .forwardEmail(apiToken: "provider-token", domain: "EXAMPLE.com"), website: "shop.example",
        )

        XCTAssertEqual(address, "alias@example.com")
    }

    /// Fastmail discovers the account before its single JMAP mutation and validates the method response.
    func test_generateFastmail_preservesTwoRequestProviderContract() async throws {
        let provider = AliasProviderTestState()
        AliasTestURLProtocol.handler = { request in
            provider.record(request)
            XCTAssertEqual(request.value(forHTTPHeaderField: "Authorization"), "Bearer provider-token")
            if request.httpMethod == "GET" {
                XCTAssertEqual(request.url?.absoluteString, "https://api.fastmail.com/.well-known/jmap")
                return .json(["primaryAccounts": ["https://www.fastmail.com/dev/maskedemail": "account-id"]])
            }
            XCTAssertEqual(request.httpMethod, "POST")
            XCTAssertEqual(request.url?.absoluteString, "https://api.fastmail.com/jmap/api/")
            let body = try AliasTestURLProtocol.jsonBody(request)
            let calls = try XCTUnwrap(body["methodCalls"] as? [[Any]])
            XCTAssertEqual(calls.count, 1)
            XCTAssertEqual(calls.first?.first as? String, "MaskedEmail/set")
            let arguments = try XCTUnwrap(calls.first?.dropFirst().first as? [String: Any])
            XCTAssertEqual(arguments["accountId"] as? String, "account-id")
            let create = try XCTUnwrap(arguments["create"] as? [String: [String: Any]])
            XCTAssertEqual(create["new-masked-email"]?["forDomain"] as? String, "shop.example")
            return .json([
                "methodResponses": [
                    ["MaskedEmail/set", ["created": ["new-masked-email": ["email": "Alias@Example.com"]]], "0"],
                ],
            ])
        }

        let address = try await makeGenerator().generate(
            service: .fastmail(apiToken: "provider-token"), website: "shop.example",
        )

        XCTAssertEqual(address, "alias@example.com")
        XCTAssertEqual(provider.recordedRequests().map(\.httpMethod), ["GET", "POST"])
    }

    /// A malformed acknowledgement after any legacy provider mutation remains uncertain.
    func test_generateLegacyProviders_malformedAcknowledgementKeepsOutcomeUnknown() async throws {
        AliasTestURLProtocol.handler = { request in
            if request.httpMethod == "GET" {
                return .json(["primaryAccounts": ["https://www.fastmail.com/dev/maskedemail": "account-id"]])
            }
            return .json([:])
        }
        let services: [ForwardedEmailGeneratorService] = [
            .addyIo(apiToken: "token", domain: "example.com", baseUrl: "https://addy.example/"),
            .firefox(apiToken: "token"), .forwardEmail(apiToken: "token", domain: "example.com"),
            .fastmail(apiToken: "token"),
        ]
        for service in services {
            do {
                _ = try await makeGenerator().generate(service: service, website: nil)
                XCTFail("Malformed acknowledgement was accepted")
            } catch {
                XCTAssertEqual(error as? EmailAliasError, .operationOutcomeUnknown)
            }
        }
    }

    /// Failed Fastmail discovery must not issue a mutation without an established account.
    func test_generateFastmail_invalidDiscoveryNeverMutates() async throws {
        let provider = AliasProviderTestState()
        AliasTestURLProtocol.handler = { request in
            provider.record(request)
            return .json([:])
        }

        do {
            _ = try await makeGenerator().generate(service: .fastmail(apiToken: "token"), website: nil)
            XCTFail("Invalid discovery was accepted")
        } catch {
            XCTAssertEqual(error as? EmailAliasError, .providerRejected)
        }
        XCTAssertEqual(provider.recordedRequests().map(\.httpMethod), ["GET"])
    }

    /// Invalid credentials fail before dispatch, including providers with a read-before-create flow.
    func test_generateLegacyProviders_invalidCredentialsNeverDispatch() async throws {
        let provider = AliasProviderTestState()
        AliasTestURLProtocol.handler = { request in
            provider.record(request)
            return .json([:])
        }
        let services: [ForwardedEmailGeneratorService] = [
            .addyIo(apiToken: "", domain: "example.com", baseUrl: "https://addy.example/"),
            .firefox(apiToken: ""), .forwardEmail(apiToken: "", domain: "example.com"), .fastmail(apiToken: ""),
        ]
        for service in services {
            do {
                _ = try await makeGenerator().generate(service: service, website: nil)
                XCTFail("Invalid credentials were accepted")
            } catch {
                XCTAssertEqual(error as? EmailAliasError, .invalidConfiguration)
            }
        }
        XCTAssertTrue(provider.recordedRequests().isEmpty)
    }

    /// Existing create-only services remain operational outside the canonical lifecycle model.
    func test_generateDuckDuckGo_preservesExistingProviderBoundary() async throws {
        let provider = AliasProviderTestState()
        AliasTestURLProtocol.handler = { request in
            provider.record(request)
            return .json(["address": "generated-local-part"])
        }
        let subject = makeGenerator()

        let address = try await subject.generate(service: .duckDuckGo(token: "provider-token"), website: nil)

        XCTAssertEqual(address, "generated-local-part@duck.com")
        XCTAssertEqual(
            provider.recordedRequests().first?.value(forHTTPHeaderField: "Authorization"),
            "Bearer provider-token",
        )
    }

    /// Addy.io shares the same endpoint boundary and must reject disguised loopback before dispatch.
    func test_generateAddyIo_rejectsNonLoopbackHTTPBeforeNetworkRequest() async throws {
        let provider = AliasProviderTestState()
        AliasTestURLProtocol.handler = { request in
            provider.record(request)
            return .json([:])
        }
        let subject = makeGenerator()

        do {
            _ = try await subject.generate(
                service: .addyIo(
                    apiToken: "provider-token",
                    domain: "example.com",
                    baseUrl: "http://127.0.0.1.attacker.example/",
                ),
                website: nil,
            )
            XCTFail("Disguised loopback endpoint was accepted")
        } catch {
            XCTAssertEqual(error as? EmailAliasError, .invalidConfiguration)
        }
        XCTAssertTrue(provider.recordedRequests().isEmpty)
    }

    /// First-class aliases cannot bypass encrypted dispatch journaling through the legacy path.
    func test_generateSimpleLogin_failsClosedWithoutNetworkRequest() async throws {
        let provider = AliasProviderTestState()
        AliasTestURLProtocol.handler = { request in
            provider.record(request)
            return .json([:])
        }
        let subject = makeGenerator()

        do {
            _ = try await subject.generate(
                service: .simpleLogin(apiKey: "provider-token", baseUrl: "https://app.simplelogin.io/"),
                website: nil,
            )
            XCTFail("The create-only compatibility path accepted a first-class provider")
        } catch {
            XCTAssertEqual(error as? EmailAliasError, .invalidConfiguration)
        }
        XCTAssertTrue(provider.recordedRequests().isEmpty)
    }
}
